"""empty message

Revision ID: 1f6276044c87
Revises: ba2f3813f480
Create Date: 2022-02-15 15:32:31.719179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f6276044c87"
down_revision = "ba2f3813f480"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("created_on", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("updated_on", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_on")
    op.drop_column("users", "created_on")
    # ### end Alembic commands ###
