"""empty message

Revision ID: 88fd869e0cc0
Revises: 
Create Date: 2022-02-16 17:47:02.395947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88fd869e0cc0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=40), nullable=True),
        sa.Column("last_name", sa.String(length=40), nullable=True),
        sa.Column("slug", sa.String(length=244), nullable=True),
        sa.Column("email", sa.String(length=244), nullable=True),
        sa.Column("password_hash", sa.String(length=244), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("slug"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
